# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - todo-task-server-01

on:
  push:
    branches:
      - railway
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_138ab609794541ce811036a1ad68f80e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f9039f94079b48b2b61b104b9aa04ab3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_138ab609794541ce811036a1ad68f80e }}/nguyendadocker/toto-task-docker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'todo-task-server-01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1634f3b7e21e4f71b15f0d70cf900fd1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_138ab609794541ce811036a1ad68f80e }}/nguyendadocker/toto-task-docker:${{ github.sha }}'